# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Jason Gallagher
title: Freelance Web Developer
email: jason@jasongallagher.co
website: www.jasongallager.co

# Social links
twitter_username: jasonrgallagher
github_username:  jgallagher5280
instagram_username: jasonrgallagher
linkedin_username: jgallagher719

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Hi, my name's Jason and I am a freelance Web Developer based in Colorado Springs, Colorado. I enjoy learning about emerging web technologies and building software that makes life just a little bit easier. 

  I am most skilled in: <mark>JavaScript</mark> and <mark>Drinking Coffee</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Climbing
   - Fortnite
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
